Update update-lambda-layer.yml

diff --git a/.github/workflows/update-lambda-layer.yml b/.github/workflows/update-lambda-layer.yml
--- a/.github/workflows/update-lambda-layer.yml
+++ b/.github/workflows/update-lambda-layer.yml
@@ -1,4 +1,4 @@
-name: Update Lambda Layer
+name: Update AWS Lambda Layer
 
 on:
   push:
@@ -6,7 +6,7 @@ on:
       - master
 
 jobs:
-  update-layer:
+  update-aws-lambda-layer:
     runs-on: ubuntu-latest
 
     steps:
@@ -61,6 +61,11 @@ jobs:
           --function-name D2R_Traderie_HTML \
           --layers arn:aws:lambda:$AWS_REGION:$AWS_ACCOUNT_ID:layer:HTML_Builder_Layer:$LAYER_VERSION
 
+  run-aws-lambda:
+    runs-on: ubuntu-latest
+    needs: update-aws-lambda-layer
+
+    steps:
     - name: Run Lambda
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -69,4 +74,9 @@ jobs:
       run: |
         aws lambda invoke \
           --function-name D2R_Traderie_HTML \
-          --payload '{}' response.json  # response.json 인자는 필수
+          --payload '{}' response.json
+        
+        if [ "$(cat response.json)" != "null" ]; then
+          echo "Lambda invocation failed with response: $(cat response.json)"
+          exit 1  # Exit with an error code
+        fi
